# network architecture
# encoder related
encoder: contextual_block_conformer    # contextual_block_conformer is the core of streaming conformer
encoder_conf:
    output_size: 256    # dimension of attention
    attention_heads: 4
    linear_units: 2048  # the number of units of position-wise feed forward
    num_blocks: 12      # the number of encoder blocks
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d # encoder architecture type
    normalize_before: true
    activation_type: swish
    macaron_style: true
    use_cnn_module: true
    cnn_module_kernel: 15
    block_size: 40      # streaming configuration
    hop_size: 16        # streaming configuration
    look_ahead: 16      # streaming configuration
    init_average: true  # streaming configuration
    ctx_pos_enc: true   # streaming configuration

# decoder related
decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

# 
model_conf:
    ctc_weight: 0.3
    report_cer: False
    report_wer: False

#
frontend: default
frontend_conf:
    hop_length: 132

# minibatch related
batch_type: folded
batch_size: 16
#valid_batch_size: 1
# optimization related
# batch_type: numel
# # batch_bins:    4500000
# batch_bins:    4000000

# optimization related
# accum_grad: 1
accum_grad: 6
grad_clip: 5
patience: null
max_epoch: 50
val_scheduler_criterion:
    - valid
    - loss
best_model_criterion:
-   - valid
    - loss
    - min
# early_stopping_criterion:
#     - valid
#     - loss
#     - min
keep_nbest_models: 10

optim: adam
optim_conf:
    lr: 0.002
scheduler: warmuplr     # pytorch v1.1.0+ required
scheduler_conf:
    warmup_steps: 25000
num_att_plot: 0
specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
